version: '3.7'
services:
    webapp:
        build: ./frontend/webapp
        image: starter-webapp
        ports:
            - 80:8080
    service:
        build: ./backend/service
        image: starter-backend-service
        ports:
            - 3001:3001
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8085:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
    reverse-proxy:
        build: dev-tools/compose-reverse-proxy
        image: starter-dev-reverse-proxy
        depends_on:
            - webapp
            - service
        ports:
            - 30000:80
        